name: "Build and test"
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          key: dist-${{ github.sha }}
          path: dist

      - name: Build
        run: |
          corepack enable
          pnpm install --frozen-lockfile && pnpm build

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          corepack enable
          pnpm install --frozen-lockfile && pnpm test

  create-artifacts:
    name: "Create artifacts"
    runs-on: ubuntu-latest
    needs:
      - build
      - test

    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          key: dist-${{ github.sha }}
          path: dist

      - name: Archive result
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  cleanup:
    name: "Cleanup"
    runs-on: ubuntu-latest
    needs:
      - create-artifacts
    permissions:
      actions: write

    steps:
      - name: Cleanup
        run: |
          gh cache delete $CACHE_KEY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          CACHE_KEY: dist-${{ github.sha }}
